cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    anutishna:
      email: a.push@gmail.com
      name: Anna K
      password: $2b$12$5DQgvTuNdPR4J/X0wvL27uz.0lbBcJZ4rfwTIvRCXoTpVNeJPVUxi
    demo:
      email: demo@mail.ru
      name: Demo
      password: $2b$12$fDLA7BP.A9xnE07lmQfpg.lV8ildJDb.oSUmj6psZ.VbhXxPrF6V.
preauthorized:
  emails:
  - melsby@gmail.com
